local api = vim.api
local function feedkeys(keys, mode)
  api.nvim_feedkeys(api.nvim_replace_termcodes(keys, true, true, true), mode, true)
end

local defualt_word_map = {
  ['true'] = 'false',
  ['True'] = 'False',
  ['TRUE'] = 'FALSE',
  ['false'] = 'true',
  ['False'] = 'True',
  ['FALSE'] = 'TRUE',
  ['yes'] = 'no',
  ['Yes'] = 'No',
  ['YES'] = 'NO',
  ['no'] = 'yes',
  ['No'] = 'Yes',
  ['NO'] = 'YES',
  ['on'] = 'off',
  ['On'] = 'Off',
  ['ON'] = 'OFF',
  ['off'] = 'on',
  ['Off'] = 'On',
  ['OFF'] = 'ON',
  ['max'] = 'min',
  ['Max'] = 'Min',
  ['MAX'] = 'MIN',
  ['min'] = 'max',
  ['Min'] = 'Max',
  ['MIN'] = 'MAX',
  ['and'] = 'or',
  ['And'] = 'Or',
  ['AND'] = 'OR',
  ['or'] = 'and',
  ['Or'] = 'And',
  ['OR'] = 'AND',
  ['+'] = '-',
  ['+='] = '-=',
  ['-'] = '+',
  ['-='] = '+=',
  ['<'] = '>',
  ['>'] = '<',
  ['=='] = '!=',
  ['!='] = '==',
  ['<='] = '>=',
  ['>='] = '<=',
  ['&'] = '|',
  ['&&'] = '||',
  ['&='] = '|=',
  ['|'] = '&',
  ['||'] = '&&',
  ['|='] = '&=',
}
