vim.keymap.set("n", "glp", ":Lspsaga peek_definition<CR>", { silent = true, noremap = true, desc = "Peek Definition" })
vim.keymap.set("n", "glr", ":Lspsaga finder<CR>", { silent = true, noremap = true, desc = "Peek reference" })
vim.keymap.set("n", "<A-x>", "<cmd>Lspsaga term_toggle<CR>")
vim.keymap.set("t", "<A-x>", "<cmd>Lspsaga term_toggle<CR>")
-- vim.keymap.set("n", "K", "<cmd>Lspsaga hover_doc<CR>", { silent = true, noremap = true, desc = "Hover Doc" })
vim.keymap.set("n", "<leader>E", "<cmd>Neotree toggle<CR>", { desc = "tree_explorer" })
vim.keymap.set("n", "<leader>aa", "<cmd>AvanteAsk<CR>", { desc = "Avante Ask" })
vim.keymap.set("n", "<leader>aA", "<cmd>CopilotChat<CR>", { desc = "CopilotChat" })
local ts_repeat_move = require("nvim-treesitter.textobjects.repeatable_move")
vim.keymap.set({ "n", "x", "o" }, "<C-w>", function()
  vim.fn.feedkeys(vim.api.nvim_replace_termcodes("<Plug>(textobj-function-i)", true, true, true))
  vim.fn.feedkeys(vim.api.nvim_replace_termcodes("<Plug>(textobj-function-a)", true, true, true))
end, { noremap = true, silent = true })
-- 毎日、私はご飯を食べます。
